[program:gunicorn]
command=/usr/local/bin/gunicorn-start.sh
PROCESS_NAME=GUNICORN
STDOUT_LOGFILE=/LOGS/SUPERVISOR/GUNICORN.LOG
STDOUT_LOGFILE_BACKUPS=3
STDERR_LOGFILE=/LOGS/SUPERVISOR/GUNICORN-ERROR.LOG
STDERR_LOGFILE_BACKUPS=3

[program:nginx]
command=/usr/sbin/nginx -g 'daemon on; master_process on;'
process_name=nginx
stdout_logfile=/logs/supervisor/nginx.log
stdout_logfile_backups=3
stderr_logfile=/logs/supervisor/nginx-error.log
stderr_logfile_backups=3
