[program:gunicorn]
command=/usr/local/bin/gunicorn-start.sh
process_name=gunicorn
stdout_logfile=/logs/supervisor/gunicorn.log
stdout_logfile_backups=3
stderr_logfile=/logs/supervisor/gunicorn-error.log
stderr_logfile_backups=3

[program:nginx]
command=/usr/sbin/nginx -g 'daemon on; master_process on;'
process_name=nginx
stdout_logfile=/logs/supervisor/nginx.log
stdout_logfile_backups=3
stderr_logfile=/logs/supervisor/nginx-error.log
stderr_logfile_backups=3

[program:logrotate]
command=/usr/sbin/logrotate /etc/logrotate.conf --debug
process_name=logrotate
stdout_logfile=/logs/supervisor/logrotate.log
stdout_logfile_backups=3
stderr_logfile=/logs/supervisor/logrotate-error.log
stderr_logfile_backups=3
