server {
    listen 80;
    listen [::]:80;
    server_name tyler-north.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443;
    listen [::]:443;
    server_name tyler-north.com;

    ssl on;
    ssl_certificate /secret/ssl.crt;
    ssl_certificate_key /secret/ssl.key;

    error_log /logs/nginx-error.log warn;
    access_log /logs/nginx-access.log;

    location /static/ {
        root /opt/website;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}

