#!/bin/sh

/usr/sbin/logrotate -v /etc/logrotate.conf &>>/logs/logrotate.log

EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE]"
fi
exit 0

