# Generated by Django 3.0.2 on 2020-01-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('my_calendar', '0004_task'), ('my_calendar', '0005_task_marked_done'), ('my_calendar', '0006_auto_20200106_0808')]

    dependencies = [
        ('my_calendar', '0003_auto_20200106_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_offset', models.IntegerField()),
                ('week_offset', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('message', models.CharField(max_length=1024)),
                ('due_date', models.DateField()),
                ('marked_done', models.BooleanField(default=False)),
            ],
        ),
    ]
