# Generated by Django 3.0.2 on 2020-01-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0004_task_squashed_0006_auto_20200106_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='marked_done',
        ),
    ]
