# Generated by Django 3.0.2 on 2020-01-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='marked_done',
            field=models.BooleanField(default=False),
        ),
    ]
