# Generated by Django 3.0.2 on 2020-01-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0005_remove_task_marked_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
