# Generated by Django 3.0.2 on 2020-01-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0005_task_marked_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='start_date',
            new_name='due_date',
        ),
    ]
