# Generated by Django 3.0.2 on 2020-01-18 07:38

from datetime import date
from django.db import migrations, models

def migrate_birthdays(apps, schema_editor):
    Birthday = apps.get_model('my_calendar', 'Birthday')
    for birthday in Birthday.objects.all():
        person = birthday.person
        today = date.today()
        birthday_date = date(today.year, birthday.month, birthday.day)
        if birthday_date < date.today():
            birthday_date = date(today.year + 1, birthday.month, birthday.day)
        person.birthday = birthday_date
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0006_auto_20200118_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_birthdays),
        migrations.DeleteModel(
            name='Birthday',
        ),
    ]
