# Generated by Django 3.0.2 on 2020-03-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0007_auto_20200118_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
