# Generated by Django 3.2.4 on 2022-03-18 01:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_calendar', '0012_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsiteUserSettings',
            new_name='UserSettings',
        ),
    ]
