# Generated by Django 3.2.4 on 2022-03-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0013_rename_websiteusersettings_usersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name_plural': 'UserSettings'},
        ),
        migrations.AddField(
            model_name='usersettings',
            name='week_start_day',
            field=models.IntegerField(default=0),
        ),
    ]
