# Generated by Django 3.2.18 on 2023-04-12 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0014_auto_20220318_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='birthdays_last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
