# Generated by Django 4.2.4 on 2023-10-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0015_usersettings_birthdays_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='person',
            name='groups',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
