# Generated by Django 3.0.7 on 2020-06-20 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Team')),
            ],
            options={
                'unique_together': {('team', 'game')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('tag', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GameRosterMemebership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Player')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.GameRoster')),
            ],
            options={
                'unique_together': {('roster', 'player')},
            },
        ),
    ]
