# Generated by Django 3.0.7 on 2020-07-08 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0002_gameroster_gamerostermemebership_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('point_differential', models.FloatField()),
                ('wins_last_eight', models.IntegerField()),
                ('losses_last_eight', models.IntegerField()),
                ('point_differential_last_eight', models.FloatField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_season', to='basketball.Team')),
            ],
        ),
    ]
