# Generated by Django 3.0.7 on 2020-07-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0003_teamseason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameRosterMemebership',
            new_name='GameRosterMembership',
        ),
    ]
