# Generated by Django 3.0.7 on 2020-08-02 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0004_auto_20200709_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(to='basketball.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Team')),
            ],
        ),
    ]
