# Generated by Django 3.0.7 on 2020-08-07 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0005_lineup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLineupStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_played', models.IntegerField()),
                ('point_differential', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Game')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Lineup')),
            ],
        ),
    ]
