# Generated by Django 3.0.7 on 2020-08-11 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0006_gamelineupstats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameroster',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gameroster',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameroster',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='gamerostermembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gamerostermembership',
            name='player',
        ),
        migrations.RemoveField(
            model_name='gamerostermembership',
            name='roster',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='players',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='team',
        ),
        migrations.DeleteModel(
            name='GameLineupStats',
        ),
        migrations.DeleteModel(
            name='GameRoster',
        ),
        migrations.DeleteModel(
            name='GameRosterMembership',
        ),
        migrations.DeleteModel(
            name='Lineup',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
