# Generated by Django 3.1.3 on 2020-11-23 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0007_auto_20200811_0329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teamseason',
            name='team',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamSeason',
        ),
    ]
