# Generated by Django 3.0.2 on 2020-01-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='person_id',
            new_name='person',
        ),
    ]
