name: Build Check

on:
  - pull_request

jobs:
  spellback:
    name: Spellcheck
    runs-on: ubuntu-24.04
    steps:
    # The checkout step
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.47.0
      name: Spellcheck
      with:
        config_path: .spellcheck/spellcheck.yml
  docker:
    name: Docker build checks
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build image
      uses: docker/build-push-action@v6
      with:
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
